-- WARNING: This script will delete existing data in students, questions, and exam_results to fix schema errors.
-- Run this if you are seeing errors like 'column "question_text" does not exist' or 'null value in id column'.

-- Drop existing tables to ensure clean schema
DROP TABLE IF EXISTS exam_results CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS students CASCADE;

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Students Table (Clean Recreate)
CREATE TABLE students (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    full_name TEXT NOT NULL,
    student_code TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Questions Table (Clean Recreate)
CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term INT NOT NULL, -- 1 for Python, 2 for C
    type TEXT NOT NULL, -- 'mcq', 'true_false', 'code_correction', 'code_output', 'theory', 'fillblank'
    question_text TEXT NOT NULL,
    options JSONB, -- For MCQs: ["Option A", "Option B", ...]
    correct_answer TEXT NOT NULL,
    explanation TEXT,
    marks INT DEFAULT 1,
    section TEXT, -- e.g., 'Part I'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Exam Results Table (Clean Recreate)
CREATE TABLE exam_results (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    student_id UUID REFERENCES students(id) ON DELETE CASCADE,
    term INT NOT NULL,
    score INT NOT NULL,
    total_possible INT NOT NULL,
    answers JSONB, -- { question_id: user_answer }
    completed_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_results ENABLE ROW LEVEL SECURITY;

-- Handle Policies
DO $$ 
BEGIN
    CREATE POLICY "Public questions are viewable by everyone" ON questions FOR SELECT USING (true);
    CREATE POLICY "Students can register themselves" ON students FOR INSERT WITH CHECK (true);
    CREATE POLICY "Students can view their own data" ON students FOR SELECT USING (true);
    CREATE POLICY "Anyone can insert results" ON exam_results FOR INSERT WITH CHECK (true);
    CREATE POLICY "Anyone can view results" ON exam_results FOR SELECT USING (true);
END $$;
