export const examData = {
  final: {
    name: "Final Exam",
    description: "25 سؤال - MCQ + Fill in the Blank + Theory",
    time: "120 دقيقة",
    marks: 50,
    questions: [
      // Section A: MCQ (Q1-Q15)
      {
        id: 1,
        section: "A",
        type: "mcq",
        question: "Which loop is preferred when the number of iterations is known?",
        options: ["while", "for", "if", "break"],
        correct: "B",
        marks: 2,
      },
      {
        id: 2,
        section: "A",
        type: "mcq",
        question: "Which keyword is used to handle errors in Python?",
        options: ["error", "try", "handle", "catch"],
        correct: "B",
        marks: 2,
      },
      {
        id: 3,
        section: "A",
        type: "mcq",
        question: "Which data type is immutable?",
        options: ["list", "set", "dictionary", "tuple"],
        correct: "D",
        marks: 2,
      },
      {
        id: 4,
        section: "A",
        type: "mcq",
        question: "What does the break statement do?",
        options: ["Skip iteration", "Exit loop completely", "Stop program", "Restart loop"],
        correct: "B",
        marks: 2,
      },
      {
        id: 5,
        section: "A",
        type: "mcq",
        question: "Which keyword is used to define a function?",
        options: ["function", "def", "define", "fun"],
        correct: "B",
        marks: 2,
      },
      {
        id: 6,
        section: "A",
        type: "mcq",
        question: "Which of the following does not allow duplicate values?",
        options: ["list", "tuple", "set", "dictionary"],
        correct: "C",
        marks: 2,
      },
      {
        id: 7,
        section: "A",
        type: "mcq",
        question: "Indexing in Python starts from:",
        options: ["1", "0", "-1", "2"],
        correct: "B",
        marks: 2,
      },
      {
        id: 8,
        section: "A",
        type: "mcq",
        question: "What does a function return if there is no return statement?",
        options: ["0", "False", "None", "Error"],
        correct: "C",
        marks: 2,
      },
      {
        id: 9,
        section: "A",
        type: "mcq",
        question: "Which block always executes whether an error occurs or not?",
        options: ["try", "except", "finally", "error"],
        correct: "C",
        marks: 2,
      },
      {
        id: 10,
        section: "A",
        type: "mcq",
        question: "Which operator requires all conditions to be true?",
        options: ["or", "and", "not", "=="],
        correct: "B",
        marks: 2,
      },
      {
        id: 11,
        section: "A",
        type: "mcq",
        question: "What is OOP?",
        options: ["A data type", "Programming using classes and objects", "Loop structure", "Error handling"],
        correct: "B",
        marks: 2,
      },
      {
        id: 12,
        section: "A",
        type: "mcq",
        question: "Which statement skips the current iteration only?",
        options: ["break", "stop", "pass", "continue"],
        correct: "D",
        marks: 2,
      },
      {
        id: 13,
        section: "A",
        type: "mcq",
        question: "What is a module?",
        options: ["Loop", "File that contains Python code", "Variable", "Error"],
        correct: "B",
        marks: 2,
      },
      {
        id: 14,
        section: "A",
        type: "mcq",
        question: "Which statement imports part of a module?",
        options: ["import math", "include math", "from math import sqrt", "math.import"],
        correct: "C",
        marks: 2,
      },
      {
        id: 15,
        section: "A",
        type: "mcq",
        question: "Why is indentation important in Python?",
        options: ["Speed", "Styling", "Defines code blocks", "Printing"],
        correct: "C",
        marks: 2,
      },
      // Section B: Fill in the blank (Q16-Q20)
      {
        id: 16,
        section: "B",
        type: "fillblank",
        question: "The keyword used to exit a loop completely is __________.",
        correct: "break",
        marks: 2,
      },
      {
        id: 17,
        section: "B",
        type: "fillblank",
        question: "A function without a return statement returns __________.",
        correct: "None",
        marks: 2,
      },
      {
        id: 18,
        section: "B",
        type: "fillblank",
        question: "The data structure that stores key-value pairs is called __________.",
        correct: "dictionary",
        marks: 2,
      },
      {
        id: 19,
        section: "B",
        type: "fillblank",
        question: "__________ is used to convert one data type into another.",
        correct: "Casting",
        marks: 2,
      },
      {
        id: 20,
        section: "B",
        type: "fillblank",
        question: "The block used to test code that may cause an error is __________.",
        correct: "try",
        marks: 2,
      },
      // Section C: Theory (Q21-Q25)
      {
        id: 21,
        section: "C",
        type: "theory",
        question: "Explain the difference between for loop and while loop.",
        correct:
          "The for loop is used when the number of iterations is known in advance, while the while loop is used when the number of iterations depends on a condition.",
        marks: 2,
      },
      {
        id: 22,
        section: "C",
        type: "theory",
        question: "What is an exception in Python?",
        correct:
          "An exception is an error that occurs during the execution of a program and may stop the program if it is not handled.",
        marks: 2,
      },
      {
        id: 23,
        section: "C",
        type: "theory",
        question: "Explain try, except, and finally.",
        correct:
          "The try block contains code that may cause an error. The except block handles the error if it occurs. The finally block executes whether an error occurs or not.",
        marks: 2,
      },
      {
        id: 24,
        section: "C",
        type: "theory",
        question: "What is the difference between list and tuple?",
        correct:
          "A list is mutable, meaning its elements can be changed, while a tuple is immutable and cannot be modified after creation.",
        marks: 2,
      },
      {
        id: 25,
        section: "C",
        type: "theory",
        question: "Explain Object Oriented Programming (OOP).",
        correct:
          "Object Oriented Programming is a programming approach that organizes code using classes and objects to make programs more organized and reusable.",
        marks: 2,
      },
    ],
  },
  mcq: {
    name: "MCQ Practice",
    description: "40 سؤال - أسئلة اختيار من متعدد",
    time: "60 دقيقة",
    marks: 40,
    questions: [
      {
        id: 1,
        type: "mcq",
        question: "Which loop is used when the number of iterations is known?",
        options: ["while", "for", "if", "try"],
        correct: "B",
      },
      {
        id: 2,
        type: "mcq",
        question: "Which loop depends on a condition to stop?",
        options: ["for", "while", "if", "break"],
        correct: "B",
      },
      {
        id: 3,
        type: "mcq",
        question: "What keyword is used to make a decision in Python?",
        options: ["loop", "if", "for", "def"],
        correct: "B",
      },
      {
        id: 4,
        type: "mcq",
        question: "Which statement is used when all conditions are false?",
        options: ["if", "elif", "else", "finally"],
        correct: "C",
      },
      {
        id: 5,
        type: "mcq",
        question: "What is an exception?",
        options: ["Syntax error", "Error during program execution", "Warning message", "Logical operator"],
        correct: "B",
      },
      {
        id: 6,
        type: "mcq",
        question: "Which block is used to test code that may cause an error?",
        options: ["except", "finally", "try", "error"],
        correct: "C",
      },
      {
        id: 7,
        type: "mcq",
        question: "Which block runs whether an error occurs or not?",
        options: ["try", "except", "error", "finally"],
        correct: "D",
      },
      {
        id: 8,
        type: "mcq",
        question: "Which data type is mutable?",
        options: ["tuple", "list", "string", "int"],
        correct: "B",
      },
      {
        id: 9,
        type: "mcq",
        question: "Which data type does not allow duplicate values?",
        options: ["list", "tuple", "set", "dictionary"],
        correct: "C",
      },
      {
        id: 10,
        type: "mcq",
        question: "Which data structure uses key-value pairs?",
        options: ["list", "tuple", "set", "dictionary"],
        correct: "D",
      },
      {
        id: 11,
        type: "mcq",
        question: "Which data type is immutable?",
        options: ["list", "dictionary", "set", "tuple"],
        correct: "D",
      },
      {
        id: 12,
        type: "mcq",
        question: "What is OOP?",
        options: ["A loop type", "A data type", "Programming using objects and classes", "Error handling method"],
        correct: "C",
      },
      {
        id: 13,
        type: "mcq",
        question: "What is a class?",
        options: ["Object instance", "Blueprint for objects", "Variable", "Function"],
        correct: "B",
      },
      {
        id: 14,
        type: "mcq",
        question: "What is an object?",
        options: ["A loop", "A function", "Instance of a class", "Module"],
        correct: "C",
      },
      {
        id: 15,
        type: "mcq",
        question: "What does self refer to?",
        options: ["Class name", "Current object", "Parent class", "Function name"],
        correct: "B",
      },
      {
        id: 16,
        type: "mcq",
        question: "What is method overriding?",
        options: [
          "Creating new class",
          "Using same variable name",
          "Redefining a method in child class",
          "Deleting method",
        ],
        correct: "C",
      },
      {
        id: 17,
        type: "mcq",
        question: "What does break do?",
        options: ["Skips iteration", "Stops program", "Exits loop completely", "Restarts loop"],
        correct: "C",
      },
      {
        id: 18,
        type: "mcq",
        question: "What does continue do?",
        options: ["Exits loop", "Skips current iteration", "Stops program", "Ends function"],
        correct: "B",
      },
      {
        id: 19,
        type: "mcq",
        question: "Indexing in Python starts from:",
        options: ["1", "-1", "0", "2"],
        correct: "C",
      },
      {
        id: 20,
        type: "mcq",
        question: "What does negative indexing do?",
        options: ["Counts from start", "Counts from middle", "Counts from end", "Causes error"],
        correct: "C",
      },
      {
        id: 21,
        type: "mcq",
        question: "What is slicing used for?",
        options: ["Delete data", "Sort data", "Extract part of sequence", "Print data"],
        correct: "C",
      },
      {
        id: 22,
        type: "mcq",
        question: "What is a module?",
        options: ["Loop", "File contains Python code", "Variable", "Error"],
        correct: "B",
      },
      {
        id: 23,
        type: "mcq",
        question: "Which keyword is used to import a module?",
        options: ["include", "using", "import", "require"],
        correct: "C",
      },
      {
        id: 24,
        type: "mcq",
        question: "Which statement imports part of a module?",
        options: ["import math", "include math", "from math import sqrt", "math.import"],
        correct: "C",
      },
      {
        id: 25,
        type: "mcq",
        question: "Why is indentation important in Python?",
        options: ["For speed", "For comments", "To define code blocks", "For variables"],
        correct: "C",
      },
      {
        id: 26,
        type: "mcq",
        question: "What is casting?",
        options: ["Printing output", "Looping data", "Converting data type", "Deleting data"],
        correct: "C",
      },
      {
        id: 27,
        type: "mcq",
        question: "Which operator has highest priority?",
        options: ["+", "*", "()", "-"],
        correct: "C",
      },
      {
        id: 28,
        type: "mcq",
        question: "Which operation is executed first?",
        options: ["Addition", "Subtraction", "Multiplication", "Parentheses"],
        correct: "D",
      },
      {
        id: 29,
        type: "mcq",
        question: "What does and operator require?",
        options: ["One condition true", "All conditions true", "No conditions", "Error"],
        correct: "B",
      },
      {
        id: 30,
        type: "mcq",
        question: "What does or operator require?",
        options: ["All conditions true", "No conditions", "One condition true", "Error"],
        correct: "C",
      },
      {
        id: 31,
        type: "mcq",
        question: "What is a function?",
        options: ["Data type", "Loop", "Reusable block of code", "Error"],
        correct: "C",
      },
      {
        id: 32,
        type: "mcq",
        question: "What keyword is used to define a function?",
        options: ["function", "def", "define", "fun"],
        correct: "B",
      },
      {
        id: 33,
        type: "mcq",
        question: "What does return do?",
        options: ["Print value", "Stop loop", "Send value from function", "Define variable"],
        correct: "C",
      },
      {
        id: 34,
        type: "mcq",
        question: "What does a function return if there is no return keyword?",
        options: ["0", "False", "None", "Error"],
        correct: "C",
      },
      {
        id: 35,
        type: "mcq",
        question: "Which of the following is a logical operator?",
        options: ["+", "*", "and", "="],
        correct: "C",
      },
      {
        id: 36,
        type: "mcq",
        question: "Which data type stores ordered items?",
        options: ["set", "list", "dictionary only", "none"],
        correct: "B",
      },
      {
        id: 37,
        type: "mcq",
        question: "Which statement skips only one iteration?",
        options: ["break", "stop", "pass", "continue"],
        correct: "D",
      },
      {
        id: 38,
        type: "mcq",
        question: "Which error happens during execution?",
        options: ["Syntax error", "Logical error", "Exception", "Indentation"],
        correct: "C",
      },
      {
        id: 39,
        type: "mcq",
        question: "Which block handles errors?",
        options: ["try", "except", "finally", "error"],
        correct: "B",
      },
      {
        id: 40,
        type: "mcq",
        question: "Which of the following is NOT a data structure?",
        options: ["list", "tuple", "if", "dictionary"],
        correct: "C",
      },
    ],
  },
}

export type ExamType = keyof typeof examData
