export const examData = {
  pythonTopGrade: {
    name: "Python Programming – Top Grade Exam (Ultra Hard)",
    description: "14 سؤال - 10 أسئلة محسوبة من الدرجات، 4 أسئلة نظرية بدون درجات",
    time: "120 دقيقة",
    marks: 16,
    questions: [
      // Section A: MCQ (Q1-Q5) - 10 Marks (2 each)
      {
        id: 1,
        section: "A",
        type: "mcq",
        question: "What is the output?\n\n```python\nx = [1, 2, 3]\ny = x\ny.append(4)\nprint(len(x))\n```",
        options: ["3", "4", "Error", "None"],
        correct: "B",
        marks: 2,
      },
      {
        id: 2,
        section: "A",
        type: "mcq",
        question: "Which statement about tuple is TRUE?",
        options: ["Mutable", "Unordered", "Allows duplicate values", "Uses keys"],
        correct: "C",
        marks: 2,
      },
      {
        id: 3,
        section: "A",
        type: "mcq",
        question: "Which keyword is used to raise an exception manually?",
        options: ["throw", "error", "raise", "except"],
        correct: "C",
        marks: 2,
      },
      {
        id: 4,
        section: "A",
        type: "mcq",
        question: "What is the output?\n\n```python\nprint(10 + 2 * 3 ** 2)\n```",
        options: ["36", "28", "22", "18"],
        correct: "B",
        marks: 2,
      },
      {
        id: 5,
        section: "A",
        type: "mcq",
        question: "Which is NOT a valid loop control statement?",
        options: ["break", "continue", "pass", "stop"],
        correct: "D",
        marks: 2,
      },
      // Section B: Code Analysis (Q6-Q8) - 6 Marks (2 each)
      {
        id: 6,
        section: "B",
        type: "codeoutput",
        question: "What is the output?\n\n```python\nfor i in range(1, 6):\n    if i % 2 == 0:\n        continue\n    print(i)\n```",
        correct: "1\n3\n5",
        marks: 2,
      },
      {
        id: 7,
        section: "B",
        type: "codeoutput",
        question: "What is the output?\n\n```python\ndef add(x, y):\n    print(x + y)\n\nresult = add(2, 3)\nprint(result)\n```",
        correct: "5\nNone",
        marks: 2,
      },
      {
        id: 8,
        section: "B",
        type: "codeoutput",
        question: "What is the output?\n\n```python\ntry:\n    print(5 / 0)\nexcept ZeroDivisionError:\n    print(\"Division Error\")\nfinally:\n    print(\"End\")\n```",
        correct: "Division Error\nEnd",
        marks: 2,
      },
      // Section C: Complete the Following (Q9-Q11) - 6 Marks (2 each)
      {
        id: 9,
        section: "C",
        type: "fillblank",
        question: "The keyword used to manually raise an exception is __________.",
        correct: "raise",
        marks: 2,
      },
      {
        id: 10,
        section: "C",
        type: "fillblank",
        question: "The data structure that stores unique values only is __________.",
        correct: "set",
        marks: 2,
      },
      {
        id: 11,
        section: "C",
        type: "fillblank",
        question: "The function keyword that sends a value back is __________.",
        correct: "return",
        marks: 2,
      },
      // Section D: Theory Questions (Q12-Q14) - 0 Marks (تدريب فقط)
      {
        id: 12,
        section: "D",
        type: "theory",
        question: "Explain operator precedence with example.",
        correct: "Operator precedence determines the order in which operators are evaluated in an expression. Example: 10 + 2 * 3 evaluates multiplication first → 10 + 6 = 16.",
        marks: 0,
      },
      {
        id: 13,
        section: "D",
        type: "theory",
        question: "Explain method overriding.",
        correct: "Method overriding is when a subclass defines a method with the same name as a method in its parent class, replacing the parent's behavior.",
        marks: 0,
      },
      {
        id: 14,
        section: "D",
        type: "theory",
        question: "Explain the difference between shallow understanding of code and deep understanding.",
        correct: "Shallow understanding means knowing what the code does at a surface level. Deep understanding means knowing why it works, how it works internally, and being able to predict edge cases.",
        marks: 0,
      },
    ],
  }, pythonAdvanced: {
    name: "Python Programming – Advanced Level",
    description: "19 سؤال - 15 أسئلة محسوبة من الدرجات، 4 أسئلة نظرية بدون درجات",
    time: "120 دقيقة",
    marks: 20,
    questions: [
      // Section A: MCQ (Q1-Q10) - 30 Marks
      {
        id: 1,
        section: "A",
        type: "mcq",
        question: "What is the output of the following?\n\n```python\nx = [1, 2, 3]\nx.append(4)\nprint(len(x))\n```",
        options: ["3", "4", "Error", "None"],
        correct: "B",
        marks: 2,
      },
      {
        id: 2,
        section: "A",
        type: "mcq",
        question: "Which loop is best when the number of iterations is unknown?",
        options: ["for", "while", "if", "def"],
        correct: "B",
        marks: 2,
      },
      {
        id: 3,
        section: "A",
        type: "mcq",
        question: "What happens if an exception is not handled?",
        options: ["Program continues", "Program stops", "Error ignored", "Loop restarts"],
        correct: "B",
        marks: 2,
      },
      {
        id: 4,
        section: "A",
        type: "mcq",
        question: "Which data structure is best to store unique values?",
        options: ["list", "tuple", "dictionary", "set"],
        correct: "D",
        marks: 2,
      },
      {
        id: 5,
        section: "A",
        type: "mcq",
        question: "Which keyword is used to exit a loop early?",
        options: ["stop", "exit", "break", "continue"],
        correct: "C",
        marks: 2,
      },
      {
        id: 6,
        section: "A",
        type: "mcq",
        question: "What does negative indexing do?",
        options: ["Causes error", "Counts from start", "Counts from end", "Deletes items"],
        correct: "C",
        marks: 2,
      },
      {
        id: 7,
        section: "A",
        type: "mcq",
        question: "Which statement correctly imports only sqrt from math module?",
        options: ["import math.sqrt", "from math import sqrt", "import sqrt from math", "math.import sqrt"],
        correct: "B",
        marks: 2,
      },
      {
        id: 8,
        section: "A",
        type: "mcq",
        question: "Which of the following is immutable?",
        options: ["list", "set", "dictionary", "tuple"],
        correct: "D",
        marks: 2,
      },
      {
        id: 9,
        section: "A",
        type: "mcq",
        question: "What does self represent in a class?",
        options: ["Class name", "Parent class", "Current object", "Module"],
        correct: "C",
        marks: 2,
      },
      {
        id: 10,
        section: "A",
        type: "mcq",
        question: "What is method overriding?",
        options: ["Deleting a method", "Creating new class", "Redefining parent method in child class", "Calling parent method"],
        correct: "C",
        marks: 2,
      },
      // Section B: Code Understanding (Q11-Q13) - 6 Marks (2 each)
      {
        id: 11,
        section: "B",
        type: "codeoutput",
        question: "What is the output?\n\n```python\nfor i in range(5):\n    if i == 3:\n        continue\n    print(i)\n```",
        correct: "0\n1\n2\n4",
        marks: 2,
      },
      {
        id: 12,
        section: "B",
        type: "codeoutput",
        question: "What is the output?\n\n```python\ndef test():\n    print(\"Hello\")\n\nresult = test()\nprint(result)\n```",
        correct: "Hello\nNone",
        marks: 2,
      },
      {
        id: 13,
        section: "B",
        type: "codeoutput",
        question: "What is the output?\n\n```python\ntry:\n    x = int(\"abc\")\nexcept:\n    print(\"Error\")\nfinally:\n    print(\"Done\")\n```",
        correct: "Error\nDone",
        marks: 2,
      },
      // Section C: Complete the Following (Q14-Q17) - 8 Marks (2 each)
      {
        id: 14,
        section: "C",
        type: "fillblank",
        question: "The data structure that does not allow duplicate values is __________.",
        correct: "set",
        marks: 2,
      },
      {
        id: 15,
        section: "C",
        type: "fillblank",
        question: "The keyword used to skip the current iteration is __________.",
        correct: "continue",
        marks: 2,
      },
      {
        id: 16,
        section: "C",
        type: "fillblank",
        question: "A function without a return statement returns __________.",
        correct: "None",
        marks: 2,
      },
      {
        id: 17,
        section: "C",
        type: "fillblank",
        question: "The block that always executes in exception handling is __________.",
        correct: "finally",
        marks: 2,
      },
      // Section D: Theory Questions (Q18-Q19) - 0 Marks (تدريب فقط)
      {
        id: 18,
        section: "D",
        type: "theory",
        question: "Explain the difference between list, tuple, and set.",
        correct: "List is ordered and mutable. Tuple is ordered and immutable. Set is unordered and does not allow duplicate values.",
        marks: 0,
      },
      {
        id: 19,
        section: "D",
        type: "theory",
        question: "Why is indentation important in Python?",
        correct: "Indentation is important because Python uses it to define code blocks, and incorrect indentation causes errors.",
        marks: 0,
      },
    ],
  }, final: {
    name: "Final Exam",
    description: "25 سؤال - MCQ + Fill in the Blank + Theory",
    time: "120 دقيقة",
    marks: 50,
    questions: [
      // Section A: MCQ (Q1-Q15)
      {
        id: 1,
        section: "A",
        type: "mcq",
        question: "Which loop is preferred when the number of iterations is known?",
        options: ["while", "for", "if", "break"],
        correct: "B",
        marks: 2,
      },
      {
        id: 2,
        section: "A",
        type: "mcq",
        question: "Which keyword is used to handle errors in Python?",
        options: ["error", "try", "handle", "catch"],
        correct: "B",
        marks: 2,
      },
      {
        id: 3,
        section: "A",
        type: "mcq",
        question: "Which data type is immutable?",
        options: ["list", "set", "dictionary", "tuple"],
        correct: "D",
        marks: 2,
      },
      {
        id: 4,
        section: "A",
        type: "mcq",
        question: "What does the break statement do?",
        options: ["Skip iteration", "Exit loop completely", "Stop program", "Restart loop"],
        correct: "B",
        marks: 2,
      },
      {
        id: 5,
        section: "A",
        type: "mcq",
        question: "Which keyword is used to define a function?",
        options: ["function", "def", "define", "fun"],
        correct: "B",
        marks: 2,
      },
      {
        id: 6,
        section: "A",
        type: "mcq",
        question: "Which of the following does not allow duplicate values?",
        options: ["list", "tuple", "set", "dictionary"],
        correct: "C",
        marks: 2,
      },
      {
        id: 7,
        section: "A",
        type: "mcq",
        question: "Indexing in Python starts from:",
        options: ["1", "0", "-1", "2"],
        correct: "B",
        marks: 2,
      },
      {
        id: 8,
        section: "A",
        type: "mcq",
        question: "What does a function return if there is no return statement?",
        options: ["0", "False", "None", "Error"],
        correct: "C",
        marks: 2,
      },
      {
        id: 9,
        section: "A",
        type: "mcq",
        question: "Which block always executes whether an error occurs or not?",
        options: ["try", "except", "finally", "error"],
        correct: "C",
        marks: 2,
      },
      {
        id: 10,
        section: "A",
        type: "mcq",
        question: "Which operator requires all conditions to be true?",
        options: ["or", "and", "not", "=="],
        correct: "B",
        marks: 2,
      },
      {
        id: 11,
        section: "A",
        type: "mcq",
        question: "What is OOP?",
        options: ["A data type", "Programming using classes and objects", "Loop structure", "Error handling"],
        correct: "B",
        marks: 2,
      },
      {
        id: 12,
        section: "A",
        type: "mcq",
        question: "Which statement skips the current iteration only?",
        options: ["break", "stop", "pass", "continue"],
        correct: "D",
        marks: 2,
      },
      {
        id: 13,
        section: "A",
        type: "mcq",
        question: "What is a module?",
        options: ["Loop", "File that contains Python code", "Variable", "Error"],
        correct: "B",
        marks: 2,
      },
      {
        id: 14,
        section: "A",
        type: "mcq",
        question: "Which statement imports part of a module?",
        options: ["import math", "include math", "from math import sqrt", "math.import"],
        correct: "C",
        marks: 2,
      },
      {
        id: 15,
        section: "A",
        type: "mcq",
        question: "Why is indentation important in Python?",
        options: ["Speed", "Styling", "Defines code blocks", "Printing"],
        correct: "C",
        marks: 2,
      },
      // Section B: Fill in the blank (Q16-Q20)
      {
        id: 16,
        section: "B",
        type: "fillblank",
        question: "The keyword used to exit a loop completely is __________.",
        correct: "break",
        marks: 2,
      },
      {
        id: 17,
        section: "B",
        type: "fillblank",
        question: "A function without a return statement returns __________.",
        correct: "None",
        marks: 2,
      },
      {
        id: 18,
        section: "B",
        type: "fillblank",
        question: "The data structure that stores key-value pairs is called __________.",
        correct: "dictionary",
        marks: 2,
      },
      {
        id: 19,
        section: "B",
        type: "fillblank",
        question: "__________ is used to convert one data type into another.",
        correct: "Casting",
        marks: 2,
      },
      {
        id: 20,
        section: "B",
        type: "fillblank",
        question: "The block used to test code that may cause an error is __________.",
        correct: "try",
        marks: 2,
      },
      // Section C: Theory (Q21-Q25)
      {
        id: 21,
        section: "C",
        type: "theory",
        question: "Explain the difference between for loop and while loop.",
        correct:
          "The for loop is used when the number of iterations is known in advance, while the while loop is used when the number of iterations depends on a condition.",
        marks: 2,
      },
      {
        id: 22,
        section: "C",
        type: "theory",
        question: "What is an exception in Python?",
        correct:
          "An exception is an error that occurs during the execution of a program and may stop the program if it is not handled.",
        marks: 2,
      },
      {
        id: 23,
        section: "C",
        type: "theory",
        question: "Explain try, except, and finally.",
        correct:
          "The try block contains code that may cause an error. The except block handles the error if it occurs. The finally block executes whether an error occurs or not.",
        marks: 2,
      },
      {
        id: 24,
        section: "C",
        type: "theory",
        question: "What is the difference between list and tuple?",
        correct:
          "A list is mutable, meaning its elements can be changed, while a tuple is immutable and cannot be modified after creation.",
        marks: 2,
      },
      {
        id: 25,
        section: "C",
        type: "theory",
        question: "Explain Object Oriented Programming (OOP).",
        correct:
          "Object Oriented Programming is a programming approach that organizes code using classes and objects to make programs more organized and reusable.",
        marks: 2,
      },
    ],
  }, mcq: {
    name: "MCQ Practice",
    description: "40 سؤال - أسئلة اختيار من متعدد",
    time: "60 دقيقة",
    marks: 40,
    questions: [
      {
        id: 1,
        type: "mcq",
        question: "Which loop is used when the number of iterations is known?",
        options: ["while", "for", "if", "try"],
        correct: "B",
      },
      {
        id: 2,
        type: "mcq",
        question: "Which loop depends on a condition to stop?",
        options: ["for", "while", "if", "break"],
        correct: "B",
      },
      {
        id: 3,
        type: "mcq",
        question: "What keyword is used to make a decision in Python?",
        options: ["loop", "if", "for", "def"],
        correct: "B",
      },
      {
        id: 4,
        type: "mcq",
        question: "Which statement is used when all conditions are false?",
        options: ["if", "elif", "else", "finally"],
        correct: "C",
      },
      {
        id: 5,
        type: "mcq",
        question: "What is an exception?",
        options: ["Syntax error", "Error during program execution", "Warning message", "Logical operator"],
        correct: "B",
      },
      {
        id: 6,
        type: "mcq",
        question: "Which block is used to test code that may cause an error?",
        options: ["except", "finally", "try", "error"],
        correct: "C",
      },
      {
        id: 7,
        type: "mcq",
        question: "Which block runs whether an error occurs or not?",
        options: ["try", "except", "error", "finally"],
        correct: "D",
      },
      {
        id: 8,
        type: "mcq",
        question: "Which data type is mutable?",
        options: ["tuple", "list", "string", "int"],
        correct: "B",
      },
      {
        id: 9,
        type: "mcq",
        question: "Which data type does not allow duplicate values?",
        options: ["list", "tuple", "set", "dictionary"],
        correct: "C",
      },
      {
        id: 10,
        type: "mcq",
        question: "Which data structure uses key-value pairs?",
        options: ["list", "tuple", "set", "dictionary"],
        correct: "D",
      },
      {
        id: 11,
        type: "mcq",
        question: "Which data type is immutable?",
        options: ["list", "dictionary", "set", "tuple"],
        correct: "D",
      },
      {
        id: 12,
        type: "mcq",
        question: "What is OOP?",
        options: ["A loop type", "A data type", "Programming using objects and classes", "Error handling method"],
        correct: "C",
      },
      {
        id: 13,
        type: "mcq",
        question: "What is a class?",
        options: ["Object instance", "Blueprint for objects", "Variable", "Function"],
        correct: "B",
      },
      {
        id: 14,
        type: "mcq",
        question: "What is an object?",
        options: ["A loop", "A function", "Instance of a class", "Module"],
        correct: "C",
      },
      {
        id: 15,
        type: "mcq",
        question: "What does self refer to?",
        options: ["Class name", "Current object", "Parent class", "Function name"],
        correct: "B",
      },
      {
        id: 16,
        type: "mcq",
        question: "What is method overriding?",
        options: [
          "Creating new class",
          "Using same variable name",
          "Redefining a method in child class",
          "Deleting method",
        ],
        correct: "C",
      },
      {
        id: 17,
        type: "mcq",
        question: "What does break do?",
        options: ["Skips iteration", "Stops program", "Exits loop completely", "Restarts loop"],
        correct: "C",
      },
      {
        id: 18,
        type: "mcq",
        question: "What does continue do?",
        options: ["Exits loop", "Skips current iteration", "Stops program", "Ends function"],
        correct: "B",
      },
      {
        id: 19,
        type: "mcq",
        question: "Indexing in Python starts from:",
        options: ["1", "-1", "0", "2"],
        correct: "C",
      },
      {
        id: 20,
        type: "mcq",
        question: "What does negative indexing do?",
        options: ["Counts from start", "Counts from middle", "Counts from end", "Causes error"],
        correct: "C",
      },
      {
        id: 21,
        type: "mcq",
        question: "What is slicing used for?",
        options: ["Delete data", "Sort data", "Extract part of sequence", "Print data"],
        correct: "C",
      },
      {
        id: 22,
        type: "mcq",
        question: "What is a module?",
        options: ["Loop", "File contains Python code", "Variable", "Error"],
        correct: "B",
      },
      {
        id: 23,
        type: "mcq",
        question: "Which keyword is used to import a module?",
        options: ["include", "using", "import", "require"],
        correct: "C",
      },
      {
        id: 24,
        type: "mcq",
        question: "Which statement imports part of a module?",
        options: ["import math", "include math", "from math import sqrt", "math.import"],
        correct: "C",
      },
      {
        id: 25,
        type: "mcq",
        question: "Why is indentation important in Python?",
        options: ["For speed", "For comments", "To define code blocks", "For variables"],
        correct: "C",
      },
      {
        id: 26,
        type: "mcq",
        question: "What is casting?",
        options: ["Printing output", "Looping data", "Converting data type", "Deleting data"],
        correct: "C",
      },
      {
        id: 27,
        type: "mcq",
        question: "Which operator has highest priority?",
        options: ["+", "*", "()", "-"],
        correct: "C",
      },
      {
        id: 28,
        type: "mcq",
        question: "Which operation is executed first?",
        options: ["Addition", "Subtraction", "Multiplication", "Parentheses"],
        correct: "D",
      },
      {
        id: 29,
        type: "mcq",
        question: "What does and operator require?",
        options: ["One condition true", "All conditions true", "No conditions", "Error"],
        correct: "B",
      },
      {
        id: 30,
        type: "mcq",
        question: "What does or operator require?",
        options: ["All conditions true", "No conditions", "One condition true", "Error"],
        correct: "C",
      },
      {
        id: 31,
        type: "mcq",
        question: "What is a function?",
        options: ["Data type", "Loop", "Reusable block of code", "Error"],
        correct: "C",
      },
      {
        id: 32,
        type: "mcq",
        question: "What keyword is used to define a function?",
        options: ["function", "def", "define", "fun"],
        correct: "B",
      },
      {
        id: 33,
        type: "mcq",
        question: "What does return do?",
        options: ["Print value", "Stop loop", "Send value from function", "Define variable"],
        correct: "C",
      },
      {
        id: 34,
        type: "mcq",
        question: "What does a function return if there is no return keyword?",
        options: ["0", "False", "None", "Error"],
        correct: "C",
      },
      {
        id: 35,
        type: "mcq",
        question: "Which of the following is a logical operator?",
        options: ["+", "*", "and", "="],
        correct: "C",
      },
      {
        id: 36,
        type: "mcq",
        question: "Which data type stores ordered items?",
        options: ["set", "list", "dictionary only", "none"],
        correct: "B",
      },
      {
        id: 37,
        type: "mcq",
        question: "Which statement skips only one iteration?",
        options: ["break", "stop", "pass", "continue"],
        correct: "D",
      },
      {
        id: 38,
        type: "mcq",
        question: "Which error happens during execution?",
        options: ["Syntax error", "Logical error", "Exception", "Indentation"],
        correct: "C",
      },
      {
        id: 39,
        type: "mcq",
        question: "Which block handles errors?",
        options: ["try", "except", "finally", "error"],
        correct: "B",
      },
      {
        id: 40,
        type: "mcq",
        question: "Which of the following is NOT a data structure?",
        options: ["list", "tuple", "if", "dictionary"],
        correct: "C",
      },
    ],
  },
}

export type ExamType = keyof typeof examData
export type ExamTypeUnion = "final" | "mcq" | "pythonAdvanced" | "pythonTopGrade"
